### PR TITLE
Move Slack icons to webroot

### PR DESCRIPTION
**Pull request by ataylorme**
Addresses #38

### CODE REVIEW

**Comment by ataylorme** [comment]
Multidev  created successfully! [http://pr-42-pantheon-wp-best-practices.pantheonsite.io/](http://pr-42-pantheon-wp-best-practices.pantheonsite.io/)

**Comment by ataylorme** [comment]
@schrapel asking for your +1 since the issue came out of our Twitter conversation. 

You can see an icon at http://pr-42-pantheon-wp-best-practices.pantheonsite.io/slack-icons/wp-cfm.png

The are also showing up in Slack properly
screen shot 2017-05-02 at 4 40 44 pm

**Comment by ataylorme** [comment]
Multidev  created successfully! [http://pr-42-pantheon-wp-best-practices.pantheonsite.io/](http://pr-42-pantheon-wp-best-practices.pantheonsite.io/)

**Review by tobeycodes — APPROVED** [review]
Makes life easier 👍

**Pull request merged**
