### PR TITLE
Use custom node docker image

### PR DESCRIPTION
**Pull request by ataylorme**

### CODE REVIEW

**Comment by ataylorme** [comment]
> [error]  Command `git -C /root/example_wordpress_composer push --force -q pantheon pr-78` failed with exit code 128 

@greg-1-anderson  is this indicative of running out of SSH keys on Pantheon? See [build 666](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/666)

**Comment by greg-1-anderson** [comment]
Could be -- I don't remember the exact error that happens, but if you have a lot of ssh keys, could well be.  I think the failure point is somewhere north of 100 keys.

**Comment by ataylorme** [comment]
@greg-1-anderson turns out the failure was not having SSH installed in my custom Docker image  😞

**Comment by ataylorme** [comment]
Visual regression test passed! 
[Visual report](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/699/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by ataylorme** [comment]
Visual regression test passed! 
[Visual report](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/704/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by tobeycodes** [comment]
I think moving a lot of this stuff to a custom docker file really complicates things for users of this tool. Unless you are planning on supporting all the things (grunt, webpack, etc) then it's really never going to be clone and play. 

I can't help but think the project has got more complicated to use recently. E.g. 

1) bash scripts inside multiple folders `.circleci`, `bin`, `scripts`
2) use bash and php scripts at the same time. `cleanup-composer` and `ScriptHandler.php` can easily be merged

I am about to start a new project on Pantheon and finding that starting from scratch is probably going to be quicker to get setup. I do appreciate all the hard work that goes into this @ataylorme but just wanted to express my current thoughts.

**Comment by ataylorme** [comment]
Thanks for the comments @schrapel. I wanted to mainly experiment with different Docker images for different build steps and see how custom Docker images effected the build time.

>  Unless you are planning on supporting all the things (grunt, webpack, etc) then it's really never going to be clone and play.

I don't mind adding Grunt and webpack as those are common but don't want my image to turn into a catch all. My thought is if someone has their own needs outside the Docker images being used here they can use those as a starting point and extend them. It would be pretty straight forward to add a few lines to the Dockerfile to get exactly what you needed then declare that in CircleCI. 

> I can't help but think the project has got more complicated to use recently

Yes, this is an ongoing effort migrating to CircleCI 2. I think the improved build times and ability to run jobs in parallel are worth it but there is more cleanup and documentation to be done.

Additionally if you want something more barebones check out [example WordPress Composer](https://github.com/pantheon-systems/example-wordpress-composer/). This repository is meant as a demonstration of how to extend that example by adding other, custom build steps you might need, such as compiling Sass.

> use bash and php scripts at the same time. cleanup-composer and ScriptHandler.php can easily be merged

Agreed, I'll open an issue to move the items in `cleanup-composer` to `ScriptHandler.php`

**Comment by ataylorme** [comment]
Using [`docker-node-Advanced-WordPress-on-Pantheon`](https://github.com/ataylorme/docker-node-Advanced-WordPress-on-Pantheon) for visual regression testing as it relies on `node` only and not PHP.

Using [`docker-php-node-pantheon`](https://github.com/ataylorme/docker-php-node-pantheon) for other steps. It includes `PHP` and `node` since build and deploy are the same step. It might be possible to break those steps out further into:
* Install Composer dependencies
* Run `node` build steps
* Deploy to Pantheon

but the overhead of multiple jobs could outweigh the benefit of using a trimmed down Docker image. Also if I add Backstop JS and a few other node tools to `docker-php-node-pantheon` then we can probably just use one Docker image for everything though I prefer showing an example of using a specific image for a specific job

@greg-1-anderson and @stevector would love to get your thoughts on this, especially around the benefits of a custom image vs. installing `node` on each build and using a custom Docker image for `example-wordpress-composer`

**Comment by ataylorme** [comment]
Possibly split into a build and test container. Maybe even separate `gulp` steps and get Node out of the PHP image

**Comment by ataylorme** [comment]
Visual regression test failed! [Visual report](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/762/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by ataylorme** [comment]
Visual regression test failed! [Visual report](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/768/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by ataylorme** [comment]
Visual regression test failed! [Visual report](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/774/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by ataylorme** [comment]
Visual regression test passed! 
[Visual report](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/784/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by ataylorme** [comment]
Visual regression test passed! 
[Visual report](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/790/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by ataylorme** [comment]
Visual regression test passed! 
[Visual report](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/799/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Pull request merged**
