### PR TITLE
Delete wp-cli.yml

### PR DESCRIPTION
**Pull request by tobeycodes**
This file is redundant when you are working out of the root of the project.

### CODE REVIEW

**Comment by ataylorme** [comment]
Visual regression test failed! [Visual report](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/709/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by ataylorme** [comment]
Visual regression test passed! 
[Visual report](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/714/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Review by ataylorme — APPROVED** [review]

**Comment by tobeycodes** [comment]
@ataylorme you'll need to change the status checks for this repo for me to merge things. It's looking for `ci/circleci` and that does not exist anymore.

**Comment by ataylorme** [comment]
@schrapel updated, going to merge this in

**Pull request merged**
