### PR TITLE
First pass at Visual Regression testing

### PR DESCRIPTION
**Pull request by ataylorme**

### CODE REVIEW

**Comment by stevector** [comment]
This docker container might be helpful: https://blog.docksal.io/visual-regression-testing-with-backstopjs-in-a-docker-container-dfd1b9ae8582

**Comment by ataylorme** [comment]
> This docker container might be helpful: https://blog.docksal.io/visual-regression-testing-with-backstopjs-in-a-docker-container-dfd1b9ae8582

Thanks for the suggestion @stevector but it's missing `apt-get` and some other packages I need. I'll probably use the `Dockerfile` though for inspiration to create my own for this repo.

**Comment by ataylorme** [comment]
Visual regression test failed! [Visual report](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/621/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by ataylorme** [comment]
Visual regression test failed! [Visual report](https://circleci.com/gh/ataylorme/Advanced-WordPress-on-Pantheon/626/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Pull request merged**
